import type { Booking, Lease, Listing, Proposal, Stay, Photo } from '../types';

// Mock Photos
const mockPhotos: Photo[] = [
  {
    id: 'photo-1',
    url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200',
    caption: 'Living Room',
    isPublished: true,
    order: 1,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'photo-2',
    url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=200',
    caption: 'Bedroom',
    isPublished: true,
    order: 2,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'photo-3',
    url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    thumbnailUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=200',
    caption: 'Kitchen',
    isPublished: true,
    order: 3,
    createdAt: new Date('2024-01-15'),
  },
];

// Mock Listings
const mockListings: Listing[] = [
  {
    id: 'listing-1',
    uniqueId: 'LST-001-ABC',
    name: 'Modern Downtown Apartment',
    address: '123 Main Street, Apt 4B',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    description: 'Beautiful modern apartment in the heart of downtown',
    photos: mockPhotos,
    features: [
      { id: 'f1', name: 'WiFi', category: 'connectivity', icon: 'wifi' },
      { id: 'f2', name: 'Air Conditioning', category: 'climate', icon: 'ac' },
    ],
    amenities: [
      { id: 'a1', name: 'Gym', category: 'fitness', icon: 'gym' },
      { id: 'a2', name: 'Pool', category: 'recreation', icon: 'pool' },
    ],
    pricing: {
      baseNightlyRate: 150,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      cleaningFee: 75,
      serviceFee: 25,
      currency: 'USD',
    },
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'listing-2',
    uniqueId: 'LST-002-DEF',
    name: 'Cozy Beach House',
    address: '456 Ocean Drive',
    city: 'Santa Monica',
    state: 'CA',
    zipCode: '90401',
    description: 'Charming beach house with ocean views',
    photos: [mockPhotos[1], mockPhotos[2]],
    features: [
      { id: 'f1', name: 'WiFi', category: 'connectivity', icon: 'wifi' },
      { id: 'f3', name: 'Parking', category: 'transport', icon: 'parking' },
    ],
    amenities: [
      { id: 'a3', name: 'Beach Access', category: 'recreation', icon: 'beach' },
    ],
    pricing: {
      baseNightlyRate: 250,
      weeklyDiscount: 15,
      monthlyDiscount: 25,
      cleaningFee: 100,
      serviceFee: 35,
      currency: 'USD',
    },
    isActive: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-07-20'),
  },
  {
    id: 'listing-3',
    uniqueId: 'LST-003-GHI',
    name: 'Mountain Retreat Cabin',
    address: '789 Pine Road',
    city: 'Lake Tahoe',
    state: 'CA',
    zipCode: '96150',
    description: 'Rustic cabin with stunning mountain views',
    photos: [mockPhotos[0]],
    features: [
      { id: 'f4', name: 'Fireplace', category: 'comfort', icon: 'fireplace' },
      { id: 'f5', name: 'Hot Tub', category: 'recreation', icon: 'hottub' },
    ],
    amenities: [
      { id: 'a4', name: 'Ski Storage', category: 'sports', icon: 'ski' },
    ],
    pricing: {
      baseNightlyRate: 200,
      weeklyDiscount: 12,
      monthlyDiscount: 22,
      cleaningFee: 85,
      serviceFee: 30,
      currency: 'USD',
    },
    isActive: true,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-08-10'),
  },
];

// Mock Proposals
const mockProposals: Proposal[] = [
  {
    id: 'proposal-1',
    uniqueId: 'PRP-001-XYZ',
    status: 'accepted',
    hcWeeksSchedule: 'Mon-Wed (Week A) / Thu-Sun (Week B)',
    weekSchedules: [
      { dayOfWeek: 0, isAvailable: false },
      { dayOfWeek: 1, isAvailable: true },
      { dayOfWeek: 2, isAvailable: true },
      { dayOfWeek: 3, isAvailable: true },
      { dayOfWeek: 4, isAvailable: false },
      { dayOfWeek: 5, isAvailable: false },
      { dayOfWeek: 6, isAvailable: false },
    ],
    draftsList: [
      { id: 'd1', version: 1, changes: 'Initial proposal', createdAt: new Date('2024-05-01'), createdBy: 'host' },
      { id: 'd2', version: 2, changes: 'Updated pricing', createdAt: new Date('2024-05-05'), createdBy: 'guest' },
    ],
    totalPrice: 4500,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-10'),
    expiresAt: new Date('2024-12-31'),
  },
  {
    id: 'proposal-2',
    uniqueId: 'PRP-002-ABC',
    status: 'pending',
    hcWeeksSchedule: 'Fri-Sun (Every Week)',
    weekSchedules: [
      { dayOfWeek: 0, isAvailable: true },
      { dayOfWeek: 1, isAvailable: false },
      { dayOfWeek: 2, isAvailable: false },
      { dayOfWeek: 3, isAvailable: false },
      { dayOfWeek: 4, isAvailable: false },
      { dayOfWeek: 5, isAvailable: true },
      { dayOfWeek: 6, isAvailable: true },
    ],
    draftsList: [
      { id: 'd3', version: 1, changes: 'Initial proposal', createdAt: new Date('2024-06-15'), createdBy: 'guest' },
    ],
    totalPrice: 7500,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
    expiresAt: new Date('2025-01-31'),
  },
  {
    id: 'proposal-3',
    uniqueId: 'PRP-003-DEF',
    status: 'countered',
    hcWeeksSchedule: 'Full Week (Alternating)',
    weekSchedules: [
      { dayOfWeek: 0, isAvailable: true },
      { dayOfWeek: 1, isAvailable: true },
      { dayOfWeek: 2, isAvailable: true },
      { dayOfWeek: 3, isAvailable: true },
      { dayOfWeek: 4, isAvailable: true },
      { dayOfWeek: 5, isAvailable: true },
      { dayOfWeek: 6, isAvailable: true },
    ],
    draftsList: [
      { id: 'd4', version: 1, changes: 'Initial proposal', createdAt: new Date('2024-07-01'), createdBy: 'host' },
      { id: 'd5', version: 2, changes: 'Counter offer', createdAt: new Date('2024-07-05'), createdBy: 'guest' },
      { id: 'd6', version: 3, changes: 'Final terms', createdAt: new Date('2024-07-08'), createdBy: 'host' },
    ],
    totalPrice: 6000,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-08'),
    expiresAt: new Date('2025-02-28'),
  },
];

// Mock Stays
const mockStays: Stay[] = [
  {
    id: 'stay-1',
    uniqueId: 'STY-001',
    checkInDate: new Date('2024-09-01'),
    checkOutDate: new Date('2024-09-04'),
    guestCount: 2,
    status: 'completed',
    totalAmount: 450,
    createdAt: new Date('2024-08-15'),
  },
  {
    id: 'stay-2',
    uniqueId: 'STY-002',
    checkInDate: new Date('2024-10-15'),
    checkOutDate: new Date('2024-10-18'),
    guestCount: 3,
    status: 'upcoming',
    totalAmount: 525,
    createdAt: new Date('2024-09-20'),
  },
  {
    id: 'stay-3',
    uniqueId: 'STY-003',
    checkInDate: new Date('2024-11-20'),
    checkOutDate: new Date('2024-11-27'),
    guestCount: 4,
    status: 'upcoming',
    totalAmount: 1400,
    createdAt: new Date('2024-10-01'),
  },
];

// Mock Leases
const mockLeases: Lease[] = [
  {
    id: 'lease-1',
    uniqueId: 'LEA-2024-001-ABCD',
    agreementNumber: 'AGR-SF-2024-0001',
    status: 'active',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-12-31'),
    listing: mockListings[0],
    proposal: mockProposals[0],
    stays: [mockStays[0], mockStays[1]],
    guestEmail: 'john.doe@email.com',
    hostEmail: 'host.sarah@splitlease.com',
    totalAmount: 4500,
    paidAmount: 3000,
    paymentStatus: 'partial',
    documentStatus: 'complete',
    isUsability: true,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'lease-2',
    uniqueId: 'LEA-2024-002-EFGH',
    agreementNumber: 'AGR-SM-2024-0002',
    status: 'pending',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2025-01-31'),
    listing: mockListings[1],
    proposal: mockProposals[1],
    stays: [],
    guestEmail: 'jane.smith@email.com',
    hostEmail: 'host.mike@splitlease.com',
    totalAmount: 7500,
    paidAmount: 0,
    paymentStatus: 'pending',
    documentStatus: 'pending',
    isUsability: false,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'lease-3',
    uniqueId: 'LEA-2024-003-IJKL',
    agreementNumber: 'AGR-LT-2024-0003',
    status: 'active',
    startDate: new Date('2024-07-15'),
    endDate: new Date('2025-02-28'),
    listing: mockListings[2],
    proposal: mockProposals[2],
    stays: [mockStays[2]],
    guestEmail: 'bob.wilson@email.com',
    hostEmail: 'host.sarah@splitlease.com',
    totalAmount: 6000,
    paidAmount: 6000,
    paymentStatus: 'paid',
    documentStatus: 'complete',
    isUsability: true,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'lease-4',
    uniqueId: 'LEA-2024-004-MNOP',
    agreementNumber: 'AGR-SF-2024-0004',
    status: 'completed',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-06-30'),
    listing: mockListings[0],
    proposal: undefined,
    stays: [],
    guestEmail: 'alice.johnson@email.com',
    hostEmail: 'host.mike@splitlease.com',
    totalAmount: 9000,
    paidAmount: 9000,
    paymentStatus: 'paid',
    documentStatus: 'complete',
    isUsability: false,
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'lease-5',
    uniqueId: 'LEA-2024-005-QRST',
    agreementNumber: 'AGR-SM-2024-0005',
    status: 'draft',
    startDate: new Date('2025-01-01'),
    endDate: new Date('2025-06-30'),
    listing: mockListings[1],
    proposal: undefined,
    stays: [],
    guestEmail: 'charlie.brown@email.com',
    hostEmail: 'host.sarah@splitlease.com',
    totalAmount: 0,
    paidAmount: 0,
    paymentStatus: 'pending',
    documentStatus: 'missing',
    isUsability: false,
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    uniqueId: 'BKG-2024-001',
    lease: mockLeases[0],
    status: 'confirmed',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'booking-2',
    uniqueId: 'BKG-2024-002',
    lease: mockLeases[1],
    status: 'pending',
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'booking-3',
    uniqueId: 'BKG-2024-003',
    lease: mockLeases[2],
    status: 'confirmed',
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'booking-4',
    uniqueId: 'BKG-2024-004',
    lease: mockLeases[3],
    status: 'completed',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'booking-5',
    uniqueId: 'BKG-2024-005',
    lease: mockLeases[4],
    status: 'pending',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
];

// Mock lease options for dropdown
export const mockLeaseOptions = mockLeases.map((lease) => ({
  id: lease.id,
  uniqueId: lease.uniqueId,
  agreementNumber: lease.agreementNumber,
  listingName: lease.listing.name,
  displayLabel: `${lease.agreementNumber} - ${lease.listing.name}`,
}));

export { mockListings, mockLeases, mockProposals, mockStays };
